name: "USB Manager"
description: "Support: https://buymeacoffee.com/leon_bell | https://ko-fi.com/leonbell | https://paypal.me/leonbell95. Identify USB devices by their responses and expose stable TCP ports. Configure everything in the Web UI."
version: "1.12.0"
url: "https://github.com/thaihoang987/addon-usb-manager"
slug: "usb_manager"
init: false
homeassistant_api: true
full_access: true
services:
  - mqtt:want
arch:
  - amd64
  - aarch64
startup: system
ingress: true
ingress_port: 8099
panel_icon: "mdi:usb-port"
panel_title: "USB Manager"
ports:
  6001/tcp: 6001
  6002/tcp: 6002
  6003/tcp: 6003
  6004/tcp: 6004
  6005/tcp: 6005
  6006/tcp: 6006
  6007/tcp: 6007
  6008/tcp: 6008
  6009/tcp: 6009
  6010/tcp: 6010
options: {}
schema: false
